/* M2C FIRST set initialisers -- generated by gen_first_sets.c */

#ifndef M2C_TOKENSET_LITERAL_T
#define M2C_TOKENSET_LITERAL_T

struct m2c_tokenset_literal_t { uint_t s0, s1, s2, n; };
typedef struct m2c_tokenset_literal_t m2c_tokenset_literal_t;

#endif /* M2C_TOKENSET_LITERAL_T */

#ifndef M2C_FIRST_SET_INITS_H
#define M2C_FIRST_SET_INITS_H

#define INIT_FIRST_OF_DEFINITION_MODULE \
  { /* bits: */ 0x00000080, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_IMPORT \
  { /* bits: */ 0x00090000, 0x00000000, 0x00000000, /* counter: */ 2 }

#define INIT_FIRST_OF_QUALIFIED_IMPORT \
  { /* bits: */ 0x00080000, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_UNQUALIFIED_IMPORT \
  { /* bits: */ 0x00010000, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_IDENT_LIST \
  { /* bits: */ 0x00000000, 0x00000200, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_DEFINITION \
  { /* bits: */ 0x10000040, 0x00000050, 0x00000000, /* counter: */ 4 }

#define INIT_FIRST_OF_CONST_DEFINITION \
  { /* bits: */ 0x00000000, 0x00000200, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_TYPE_DEFINITION \
  { /* bits: */ 0x00000000, 0x00000200, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_TYPE \
  { /* bits: */ 0x58000004, 0x00000202, 0x00000050, /* counter: */ 8 }

#define INIT_FIRST_OF_DERIVED_OR_SUBRANGE_TYPE \
  { /* bits: */ 0x00000000, 0x00000200, 0x00000040, /* counter: */ 2 }

#define INIT_FIRST_OF_QUALIDENT \
  { /* bits: */ 0x00000000, 0x00000200, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_RANGE \
  { /* bits: */ 0x00000000, 0x00000000, 0x00000040, /* counter: */ 1 }

#define INIT_FIRST_OF_ENUM_TYPE \
  { /* bits: */ 0x00000000, 0x00000000, 0x00000010, /* counter: */ 1 }

#define INIT_FIRST_OF_SET_TYPE \
  { /* bits: */ 0x00000000, 0x00000002, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_COUNTABLE_TYPE \
  { /* bits: */ 0x00000000, 0x00000200, 0x00000050, /* counter: */ 3 }

#define INIT_FIRST_OF_ARRAY_TYPE \
  { /* bits: */ 0x00000004, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_EXTENSIBLE_RECORD_TYPE \
  { /* bits: */ 0x40000000, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_FIELD_LIST_SEQUENCE \
  { /* bits: */ 0x00000000, 0x00000200, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_VARIANT_RECORD_TYPE \
  { /* bits: */ 0x40000000, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_VARIANT_FIELD_LIST_SEQ \
  { /* bits: */ 0x00000020, 0x00000200, 0x00000000, /* counter: */ 2 }

#define INIT_FIRST_OF_VARIANT_FIELD_LIST \
  { /* bits: */ 0x00000020, 0x00000200, 0x00000000, /* counter: */ 2 }

#define INIT_FIRST_OF_VARIANT_FIELDS \
  { /* bits: */ 0x00000020, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_VARIANT \
  { /* bits: */ 0x01000000, 0x000C3E00, 0x00000110, /* counter: */ 10 }

#define INIT_FIRST_OF_CASE_LABEL_LIST \
  { /* bits: */ 0x01000000, 0x000C3E00, 0x00000110, /* counter: */ 10 }

#define INIT_FIRST_OF_CASE_LABELS \
  { /* bits: */ 0x01000000, 0x000C3E00, 0x00000110, /* counter: */ 10 }

#define INIT_FIRST_OF_POINTER_TYPE \
  { /* bits: */ 0x08000000, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_PROCEDURE_TYPE \
  { /* bits: */ 0x10000000, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_SIMPLE_FORMAL_TYPE \
  { /* bits: */ 0x00000004, 0x00000200, 0x00000000, /* counter: */ 2 }

#define INIT_FIRST_OF_PROCEDURE_HEADER \
  { /* bits: */ 0x10000000, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_PROCEDURE_SIGNATURE \
  { /* bits: */ 0x00000000, 0x00000200, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_SIMPLE_FORMAL_PARAMS \
  { /* bits: */ 0x00000000, 0x00000200, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_IMPLEMENTATION_MODULE \
  { /* bits: */ 0x00040000, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_PROGRAM_MODULE \
  { /* bits: */ 0x00800000, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_MODULE_PRIORITY \
  { /* bits: */ 0x00000000, 0x00000000, 0x00000040, /* counter: */ 1 }

#define INIT_FIRST_OF_BLOCK \
  { /* bits: */ 0x10801048, 0x00000050, 0x00000000, /* counter: */ 7 }

#define INIT_FIRST_OF_DECLARATION \
  { /* bits: */ 0x10800040, 0x00000050, 0x00000000, /* counter: */ 5 }

#define INIT_FIRST_OF_TYPE_DECLARATION \
  { /* bits: */ 0x00000000, 0x00000200, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_VAR_SIZE_RECORD_TYPE \
  { /* bits: */ 0x00000000, 0x00000040, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_VARIABLE_DECLARATION \
  { /* bits: */ 0x00000000, 0x00000200, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_PROCEDURE_DECLARATION \
  { /* bits: */ 0x10000000, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_MODULE_DECLARATION \
  { /* bits: */ 0x00800000, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_EXPORT \
  { /* bits: */ 0x00004000, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_STATEMENT_SEQUENCE \
  { /* bits: */ 0x8022A020, 0x00000381, 0x00000000, /* counter: */ 10 }

#define INIT_FIRST_OF_STATEMENT \
  { /* bits: */ 0x8022A020, 0x00000381, 0x00000000, /* counter: */ 10 }

#define INIT_FIRST_OF_ASSIGNMENT_OR_PROC_CALL \
  { /* bits: */ 0x00000000, 0x00000200, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_ACTUAL_PARAMETERS \
  { /* bits: */ 0x00000000, 0x00000000, 0x00000010, /* counter: */ 1 }

#define INIT_FIRST_OF_EXPRESSION_LIST \
  { /* bits: */ 0x01000000, 0x000C3E00, 0x00000110, /* counter: */ 10 }

#define INIT_FIRST_OF_RETURN_STATEMENT \
  { /* bits: */ 0x00000000, 0x00000001, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_WITH_STATEMENT \
  { /* bits: */ 0x00000000, 0x00000100, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_IF_STATEMENT \
  { /* bits: */ 0x00020000, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_CASE_STATEMENT \
  { /* bits: */ 0x00000020, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_CASE \
  { /* bits: */ 0x01000000, 0x000C3E00, 0x00000110, /* counter: */ 10 }

#define INIT_FIRST_OF_LOOP_STATEMENT \
  { /* bits: */ 0x00200000, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_WHILE_STATEMENT \
  { /* bits: */ 0x00000000, 0x00000080, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_REPEAT_STATEMENT \
  { /* bits: */ 0x80000000, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_FOR_STATEMENT \
  { /* bits: */ 0x00008000, 0x00000000, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_DESIGNATOR \
  { /* bits: */ 0x00000000, 0x00000200, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_SELECTOR \
  { /* bits: */ 0x00000000, 0x40000000, 0x00000044, /* counter: */ 3 }

#define INIT_FIRST_OF_EXPRESSION \
  { /* bits: */ 0x01000000, 0x000C3E00, 0x00000110, /* counter: */ 10 }

#define INIT_FIRST_OF_SIMPLE_EXPRESSION \
  { /* bits: */ 0x01000000, 0x000C3E00, 0x00000110, /* counter: */ 10 }

#define INIT_FIRST_OF_TERM \
  { /* bits: */ 0x01000000, 0x00003E00, 0x00000110, /* counter: */ 8 }

#define INIT_FIRST_OF_SIMPLE_TERM \
  { /* bits: */ 0x01000000, 0x00003E00, 0x00000110, /* counter: */ 8 }

#define INIT_FIRST_OF_FACTOR \
  { /* bits: */ 0x00000000, 0x00003E00, 0x00000110, /* counter: */ 7 }

#define INIT_FIRST_OF_DESIGNATOR_OR_FUNC_CALL \
  { /* bits: */ 0x00000000, 0x00000200, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_SET_VALUE \
  { /* bits: */ 0x00000000, 0x00000000, 0x00000100, /* counter: */ 1 }

#define INIT_FIRST_OF_ELEMENT \
  { /* bits: */ 0x01000000, 0x000C3E00, 0x00000110, /* counter: */ 10 }

#define INIT_FIRST_OF_FORMAL_TYPE \
  { /* bits: */ 0x00000044, 0x00000240, 0x00000000, /* counter: */ 4 }

#define INIT_FIRST_OF_ATTRIBUTED_FORMAL_TYPE \
  { /* bits: */ 0x00000040, 0x00000040, 0x00000000, /* counter: */ 2 }

#define INIT_FIRST_OF_FORMAL_PARAM_LIST \
  { /* bits: */ 0x00000040, 0x00000240, 0x00000000, /* counter: */ 3 }

#define INIT_FIRST_OF_FORMAL_PARAMS \
  { /* bits: */ 0x00000040, 0x00000240, 0x00000000, /* counter: */ 3 }

#define INIT_FIRST_OF_ATTRIB_FORMAL_PARAMS \
  { /* bits: */ 0x00000040, 0x00000040, 0x00000000, /* counter: */ 2 }

#define INIT_FIRST_OF_TYPE_DECLARATION_TAIL \
  { /* bits: */ 0x58000004, 0x00000242, 0x00000050, /* counter: */ 9 }

#define INIT_FIRST_OF_ALT_FORMAL_TYPE \
  { /* bits: */ 0x00000004, 0x00000240, 0x00000000, /* counter: */ 3 }

#define INIT_FIRST_OF_ALT_ATTRIB_FORMAL_TYPE \
  { /* bits: */ 0x00000000, 0x00000040, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_ALT_FORMAL_PARAM_LIST \
  { /* bits: */ 0x00000000, 0x00000240, 0x00000000, /* counter: */ 2 }

#define INIT_FIRST_OF_ALT_FORMAL_PARAMS \
  { /* bits: */ 0x00000000, 0x00000240, 0x00000000, /* counter: */ 2 }

#define INIT_FIRST_OF_ALT_ATTRIB_FORMAL_PARAMS \
  { /* bits: */ 0x00000000, 0x00000040, 0x00000000, /* counter: */ 1 }

#define INIT_FIRST_OF_ALT_TYPE_DECL_TAIL \
  { /* bits: */ 0x58000004, 0x00000202, 0x00000050, /* counter: */ 8 }

#endif /* M2C_FIRST_SET_INITS_H */

/* END OF FILE */
