/* m2-build-params.h -- build parameters for m2c -- public domain file */

#ifndef M2C_BUILD_PARAMS_H
#define M2C_BUILD_PARAMS_H

#define M2C_BUILD_NUMBER 1

#define M2C_COROUTINES_IMPLEMENTED 0

#define M2C_LOCAL_MODULES_IMPLEMENTED 0

#define M2C_VARIANT_RECORDS_IMPLEMENTED 1

#define M2C_COMMENT_PRESRVN_IMPLEMENTED 0

#define M2C_LIBNAME_XLATION_IMPLEMENTED 0

#define M2C_MAX_C_MACRO_LENGTH 64

#define M2C_MAX_C_IDENT_LENGTH 32

#endif /* M2C_BUILD_PARAMS_H */

/* END OF FILE */